---
title: "satellite_image_sentinel"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

gdalcubes::gdalcubes_options(threads = parallel::detectCores() - 1)

# devtools::install_github("r-spatial/stars")
library(stars)
library(mapedit)
library(mapview)
library(ggplot2)
library(mdseo)
library(tmap)
library(sf)

lonlat2UTM = function(lonlat) {
  utm = (floor((lonlat[1] + 180) / 6) %% 60) + 1
  if(lonlat[2] > 0) {
    utm + 32600
  } else{
    utm + 32700
  }
}
```


## AOI

```{r}
aoi = mapedit::editMap()
# st_write(aoi, dsn = "aoi_eastern_alps.geojson", delete_dsn = TRUE)
# st_write(aoi, dsn = "aoi_pucon.geojson", delete_dsn = TRUE)
# st_write(aoi, dsn = "aoi_putre.geojson", delete_dsn = TRUE)
# st_write(aoi, dsn = "aoi_karijini.geojson", delete_dsn = TRUE)
```


## Sentinel data

### Karijini National Park

```{r karijini_aoi, eval = FALSE}
aoi_name = "karijini"
aoi = st_read(paste0("aoi_", aoi_name, ".geojson"))
utm = st_centroid(aoi) |> 
  st_coordinates() |> 
  lonlat2UTM()

aoi = prepAOI(aoi, crs_cube = utm)
```

Image assessment...

```{r karijini_pre, eval = FALSE}
rc = defineCube(
  aoi
  , cube_opts = cubeOpts(
    dx = 100
    , dt = "P4D"
    , period = c("2020-01-01", "2020-12-31")
  )
) |> 
  listCollections() |> 
  rasterCube() |> 
  st_as_stars() |> 
  cleanCube(which = 3)

readr::write_rds(rc, file = paste0("data/rc_", aoi_name, "_pre.rds"), compress = "gz")
rc = readr::read_rds(file = paste0("data/rc_", aoi_name, "_pre.rds"))

rc_b2d = rc |> 
  stars::st_as_stars() |> 
  # bands to dimension
  merge() |> 
  setNames(nm = "value") |> 
  stars::st_set_dimensions(which = 4, names = "band")

plot(rc_b2d[,,,6], rgb = 4:2)
```


```{r karijini, eval = FALSE}
rc = defineCube(
  aoi
  , cube_opts = cubeOpts(
    dx = 10
    , period = c("2021-10-27", "2021-10-30")
  )
) |> 
  listCollections() |> 
  rasterCube() |> 
  st_as_stars() |> 
  abind::adrop()

readr::write_rds(rc, file = paste0("data/rc_", aoi_name, ".rds"), compress = "gz")
rc = readr::read_rds(file = paste0("data/rc_", aoi_name, ".rds"))

rc_b2d = rc |> 
  stars::st_as_stars() |> 
  # bands to dimension
  merge() |> 
  setNames(nm = "value") |> 
  stars::st_set_dimensions(which = 3, names = "band")

# true/false color image
# plot(rc_b2d, rgb = 4:2)

rc_b2d_hex = rc_b2d[,,, 4:2] |> 
  stars::st_rgb(dimension = 3
                , maxColorValue = 65000
                , probs = c(0.01, 0.99)
                , stretch = TRUE) 

p = ggplot() +
  stars::geom_stars(data = rc_b2d_hex) + 
  scale_fill_identity() + 
  coord_equal() + 
  theme_void()

ggsave(paste0("img/", aoi_name, ".jpg")
       , plot = p
       , device = "jpeg"
       , width = 600
       , height = 400
       , units = "mm"
       , dpi = "print")
```


### Putre Chilenean Coast

```{r putre_aoi, eval = FALSE}
aoi_name = "putre"
aoi = st_read(paste0("aoi_", aoi_name, ".geojson"))
utm = st_centroid(aoi) |> 
  st_coordinates() |> 
  lonlat2UTM()

aoi = prepAOI(aoi, crs_cube = utm)
```

```{r putre_pre, eval = FALSE}
rc = defineCube(
  aoi
  , cube_opts = cubeOpts(
    dx = 250
    , aggregation = "min"
    # , dt = "P4D"
    , period = c("2021-06-01", "2021-06-30")
  )
) |> 
  listCollections() |> 
  rasterCube() |> 
  st_as_stars() # |> 
  # cleanCube(which = 3)

readr::write_rds(rc, file = paste0("data/rc_", aoi_name, "_pre.rds"), compress = "gz")
rc = readr::read_rds(file = paste0("data/rc_", aoi_name, "_pre.rds"))

rc_b2d = rc |> 
  stars::st_as_stars() |> 
  # bands to dimension
  merge() |> 
  setNames(nm = "value") |> 
  stars::st_set_dimensions(which = 4, names = "band")

plot(rc_b2d, rgb = 3:1)

dim(rc_b2d)
st_get_dimension_values(rc_b2d, which = 3)

```

```{r putre, eval = FALSE}
rc = defineCube(
  aoi
  , cube_opts = cubeOpts(
    dx = 10
    , period = c("2021-10-27", "2021-10-30")
  )
) |> 
  listCollections() |> 
  rasterCube() |> 
  st_as_stars() 

readr::write_rds(rc, file = paste0("data/rc_", aoi_name, ".rds"), compress = "gz")
rc = readr::read_rds(file = paste0("data/rc_", aoi_name, ".rds"))

rc_b2d = rc |> 
  stars::st_as_stars() |> 
  # bands to dimension
  merge() |> 
  setNames(nm = "value") |> 
  stars::st_set_dimensions(which = 4, names = "band")

# true/false color image
st_get_dimension_values(rc, which = 3)
plot(rc_b2d[,,,6], rgb = 4:2)
rc_b2d_hex = rc_b2d[,,, 1, 4:2] |> 
  stars::st_rgb(dimension = 4
                , maxColorValue = 65000
                , probs = c(0.01, 0.99)
                , stretch = TRUE) 

rc_b2d_hex |> 
  tm_shape() + 
  tm_raster()

rc[,,, 1] |> 
  tm_shape() + 
  tm_rgb(r = 4, g = 3, b = 2)

  
ggplot() +
  stars::geom_stars(data = rc_b2d_hex) + 
  scale_fill_identity() + 
  coord_equal() + 
  theme_void()

ggsave(paste0("img/", aoi_name, ".jpg")
       , device = "jpeg"
       , width = 600
       , height = 400
       , units = "mm"
       , dpi = "print")
```

